 include:
 - board: seeeduino_xiao_ble
   shield: roBa_DONGLE
   snippet: studio-rpc-usb-uart
 - board: seeeduino_xiao_ble
   shield: roBa_L
 - board: seeeduino_xiao_ble
   shield: roBa_R
 - board: seeeduino_xiao_ble
   shield: settings_reset
